name = "cortex-prime"
main = "src/index.js"
compatibility_date = "2024-03-09"
workers_dev = true

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "vector-index"

[[d1_databases]]
binding = "DB"
database_name = "leverage-ttrpg"
database_id = "08cb77d0-7306-4441-a01f-9b5d52345bdc"
